/* 한글 Studio v3 課程資料：內容與互動引擎分離，之後擴課不必改主程式。 */
window.HANGUL_COURSE_DATA = {
  version: '3.3.0-preview',
  lessons: [
    {
      id: 'blocks', number: '01', minutes: 4, title: '先看懂韓文字塊',
      kicker: '一格就是一個音節',
      goal: '知道韓文不是圖案，而是「初聲＋母音＋可選收尾」拼成的積木。',
      note: '母音形狀決定左右排或上下排；先會拆，之後遇到沒背過的字也能試著讀。',
      sounds: [
        { letter: '가', sample: '가', roman: 'ga', hint: 'ㄱ ＋ ㅏ' },
        { letter: '고', sample: '고', roman: 'go', hint: 'ㄱ ＋ ㅗ' },
        { letter: '한', sample: '한', roman: 'han', hint: 'ㅎ ＋ ㅏ ＋ ㄴ' },
        { letter: '글', sample: '글', roman: 'geul', hint: 'ㄱ ＋ ㅡ ＋ ㄹ' },
      ],
      compare: [['가', '고', '한', '글']],
    },
    {
      id: 'lax', number: '02', minutes: 6, title: '鬆音', kicker: '輕鬆開始，不要硬擠',
      goal: '先抓住 ㄱ、ㄷ、ㅂ、ㅅ、ㅈ 五個基本家族。',
      note: '鬆音在單字位置不同時會有些音感變化；現在先聽完整音節，不用硬套華語注音。',
      sounds: [
        { letter:'ㄱ', sample:'가', roman:'g/k', hint:'가' }, { letter:'ㄷ', sample:'다', roman:'d/t', hint:'다' },
        { letter:'ㅂ', sample:'바', roman:'b/p', hint:'바' }, { letter:'ㅅ', sample:'사', roman:'s', hint:'사' },
        { letter:'ㅈ', sample:'자', roman:'j', hint:'자' },
      ],
      compare: [['가','다','바','사','자']],
    },
    {
      id: 'tense', number: '03', minutes: 6, title: '緊音', kicker: '短、緊、乾淨',
      goal: '能把 ㄲ、ㄸ、ㅃ、ㅆ、ㅉ 和鬆音分開。',
      note: '緊音不是更大聲，也不是吐更多氣；感覺像先把聲門繃住，再短促放出。',
      sounds: [
        { letter:'ㄲ', sample:'까', roman:'kk', hint:'까' }, { letter:'ㄸ', sample:'따', roman:'tt', hint:'따' },
        { letter:'ㅃ', sample:'빠', roman:'pp', hint:'빠' }, { letter:'ㅆ', sample:'싸', roman:'ss', hint:'싸' },
        { letter:'ㅉ', sample:'짜', roman:'jj', hint:'짜' },
      ],
      compare: [['가','까'],['다','따'],['바','빠'],['사','싸'],['자','짜']],
    },
    {
      id: 'aspirated', number: '04', minutes: 6, title: '送氣音與 ㅎ', kicker: '手掌放嘴前，感受氣流',
      goal: '認出 ㅋ、ㅌ、ㅍ、ㅊ，並把 ㅎ 放進氣流家族理解。',
      note: 'ㅋ／ㅌ／ㅍ／ㅊ 是送氣音；ㅎ 本身是帶明顯氣流的音，也會影響相鄰子音。',
      sounds: [
        { letter:'ㅋ', sample:'카', roman:'k', hint:'카' }, { letter:'ㅌ', sample:'타', roman:'t', hint:'타' },
        { letter:'ㅍ', sample:'파', roman:'p', hint:'파' }, { letter:'ㅊ', sample:'차', roman:'ch', hint:'차' },
        { letter:'ㅎ', sample:'하', roman:'h', hint:'하' },
      ],
      compare: [['가','까','카'],['다','따','타'],['바','빠','파'],['자','짜','차']],
    },
    {
      id: 'resonants', number: '05', minutes: 7, title: '鼻音／流音', kicker: '讓聲音延續',
      goal: '學會 ㄴ、ㅁ、ㅇ、ㄹ，並知道 ㅇ、ㄹ 放前面和下面不一樣。',
      note: '初聲 ㅇ 不發音，只負責承接母音；ㄹ 在開頭是短促彈舌，放在收尾時接近 l。',
      sounds: [
        { letter:'ㄴ', sample:'나', roman:'n', hint:'舌尖頂上齒齦' }, { letter:'ㅁ', sample:'마', roman:'m', hint:'雙唇閉合' },
        { letter:'ㅇ', sample:'아', roman:'silent', hint:'初聲不發音' }, { letter:'ㄹ', sample:'라', roman:'r/l', hint:'舌尖輕彈' },
      ],
      compare: [['나','마','아','라'],['아','앙'],['라','알']],
    },
    {
      id: 'basic-vowels', number: '06', minutes: 9, title: '六個基本母音', kicker: '口型比注音重要',
      goal: '聽出 ㅏ、ㅓ、ㅗ、ㅜ、ㅡ、ㅣ 的核心口型。',
      note: 'ㅓ、ㅡ 在華語沒有一對一對應；把注音當起點，最後以真人音檔為準。',
      sounds: [
        { letter:'ㅏ', sample:'아', roman:'a', hint:'嘴自然張開' }, { letter:'ㅓ', sample:'어', roman:'eo', hint:'嘴放鬆張開' },
        { letter:'ㅗ', sample:'오', roman:'o', hint:'嘴圓、舌位較高' }, { letter:'ㅜ', sample:'우', roman:'u', hint:'嘴圓向前' },
        { letter:'ㅡ', sample:'으', roman:'eu', hint:'嘴角拉平' }, { letter:'ㅣ', sample:'이', roman:'i', hint:'嘴角微拉' },
      ],
      compare: [['아','어'],['오','우'],['으','이']],
    },
    {
      id: 'y-vowels', number: '07', minutes: 6, title: 'Y 系母音', kicker: '多一短橫，多一個 y',
      goal: '用基本母音推導 ㅑ、ㅕ、ㅛ、ㅠ。',
      note: '不要重新背四個孤立符號；把它們理解成 ya、yeo、yo、yu。',
      sounds: [
        { letter:'ㅑ', sample:'야', roman:'ya', hint:'ㅏ → ㅑ' }, { letter:'ㅕ', sample:'여', roman:'yeo', hint:'ㅓ → ㅕ' },
        { letter:'ㅛ', sample:'요', roman:'yo', hint:'ㅗ → ㅛ' }, { letter:'ㅠ', sample:'유', roman:'yu', hint:'ㅜ → ㅠ' },
      ],
      compare: [['아','야'],['어','여'],['오','요'],['우','유']],
    },
    {
      id: 'compound-vowels', number: '08', minutes: 8, title: 'W 系與可雙讀母音', kicker: '先分標準分類，再聽現代口音',
      goal: '認出 ㅐ／ㅔ 系與 ㅘ、ㅝ 等複合母音，也知道 ㅚ／ㅟ 的兩種標準讀法。',
      note: 'ㅚ、ㅟ 在標準發音法原則上列為單母音，也允許念成帶 w 滑音的雙母音；現代首爾口語常聽到後者。',
      sounds: [
        { letter:'ㅐ', sample:'애', roman:'ae', hint:'現代音近 ㅔ' }, { letter:'ㅔ', sample:'에', roman:'e', hint:'現代音近 ㅐ' },
        { letter:'ㅘ', sample:'와', roman:'wa', hint:'ㅗ＋ㅏ' }, { letter:'ㅝ', sample:'워', roman:'wo', hint:'ㅜ＋ㅓ' },
        { letter:'ㅚ', sample:'외', roman:'oe/we', hint:'原則單母音；也可近 we' }, { letter:'ㅟ', sample:'위', roman:'wi', hint:'原則單母音；也可帶 w 滑音' },
      ],
      compare: [['애','에'],['와','워'],['외','위']],
    },
    {
      id: 'ui-review', number: '09', minutes: 8, title: 'ㅢ 與 40 音總整理', kicker: '最後一塊拼圖',
      goal: '知道 ㅢ 的核心音與常見位置變化，完成 40 音地圖。',
      note: 'ㅢ 單獨或詞首保留核心音；有子音初聲時必須念 ㅣ，非詞首 의 可念 ㅣ，助詞 의 也可念 에。',
      sounds: [
        { letter:'ㅢ', sample:'의', roman:'ui', hint:'先 ㅡ 再滑向 ㅣ' },
        { letter:'희', sample:'희', roman:'hi', hint:'子音初聲＋ㅢ 必須念 ㅣ' },
        { letter:'나의', sample:'나의', roman:'na-ui', hint:'助詞 의 常可近 e' },
      ],
      compare: [['의','이','에']],
    },
  ],
  matrixGroups: [
    { id:'basic', label:'基本表', consonants:['ㄱ','ㄴ','ㄷ','ㄹ','ㅁ','ㅂ','ㅅ','ㅇ','ㅈ','ㅎ'], vowels:['ㅏ','ㅓ','ㅗ','ㅜ','ㅡ','ㅣ'] },
    { id:'y', label:'Y 系', consonants:['ㄱ','ㄴ','ㄷ','ㄹ','ㅁ','ㅂ','ㅅ','ㅇ','ㅈ','ㅎ'], vowels:['ㅑ','ㅕ','ㅛ','ㅠ'] },
    { id:'compound', label:'複合母音', consonants:['ㄱ','ㄴ','ㄷ','ㄹ','ㅁ','ㅂ','ㅅ','ㅇ','ㅈ','ㅎ'], vowels:['ㅐ','ㅔ','ㅒ','ㅖ','ㅘ','ㅙ','ㅚ','ㅝ','ㅞ','ㅟ','ㅢ'] },
    { id:'contrast', label:'鬆緊送氣', consonants:['ㄱ','ㄲ','ㅋ','ㄷ','ㄸ','ㅌ','ㅂ','ㅃ','ㅍ','ㅅ','ㅆ','ㅈ','ㅉ','ㅊ','ㅎ'], vowels:['ㅏ','ㅓ','ㅗ','ㅜ','ㅡ','ㅣ'] },
    { id:'resonants', label:'鼻／流音', consonants:['ㄴ','ㅁ','ㅇ','ㄹ'], vowels:['ㅏ','ㅓ','ㅗ','ㅜ','ㅡ','ㅣ'] },
    { id:'all', label:'完整 399', consonants:['ㄱ','ㄲ','ㄴ','ㄷ','ㄸ','ㄹ','ㅁ','ㅂ','ㅃ','ㅅ','ㅆ','ㅇ','ㅈ','ㅉ','ㅊ','ㅋ','ㅌ','ㅍ','ㅎ'], vowels:['ㅏ','ㅐ','ㅑ','ㅒ','ㅓ','ㅔ','ㅕ','ㅖ','ㅗ','ㅘ','ㅙ','ㅚ','ㅛ','ㅜ','ㅝ','ㅞ','ㅟ','ㅠ','ㅡ','ㅢ','ㅣ'] },
  ],
  // 依發音位置排序；每一張都先聽單獨音節，再進入有意思的例字。
  singleBatchim: [
    { id:'k', sound:'ㄱ', roman:'k', standalone:'악', cue:'舌根抵住軟顎，氣流停住，不把 k 爆出來。', spellings:['ㄱ','ㄲ','ㅋ'], example:{ word:'책', mean:'書' } },
    { id:'n', sound:'ㄴ', roman:'n', standalone:'안', cue:'舌尖頂住齒齦，讓鼻音 n 留在下面。', spellings:['ㄴ'], example:{ word:'손', mean:'手' } },
    { id:'m', sound:'ㅁ', roman:'m', standalone:'암', cue:'雙唇閉合，讓鼻音 m 留在下面。', spellings:['ㅁ'], example:{ word:'밤', mean:'夜晚' } },
    { id:'ng', sound:'ㅇ', roman:'ng', standalone:'앙', cue:'舌根抬起、聲音走鼻腔；ㅇ 放在下面才念 ng。', spellings:['ㅇ'], example:{ word:'강', mean:'江／河' } },
    { id:'l', sound:'ㄹ', roman:'l', standalone:'알', cue:'舌尖貼住齒齦就停下，接近英文 l，不要捲成「兒」。', spellings:['ㄹ'], example:{ word:'물', mean:'水' } },
    { id:'t', sound:'ㄷ', roman:'t', standalone:'앋', cue:'舌尖抵住齒齦，氣流停住，不把 t 爆出來。', spellings:['ㄷ','ㅅ','ㅆ','ㅈ','ㅊ','ㅌ','ㅎ'], example:{ word:'옷', mean:'衣服' } },
    { id:'p', sound:'ㅂ', roman:'p', standalone:'압', cue:'雙唇閉住，氣流停住，不把 p 爆出來。', spellings:['ㅂ','ㅍ'], example:{ word:'밥', mean:'飯' } },
  ],
  doubleBatchimGroups: [
    {
      sound:'ㄱ', label:'留下 ㄱ 音',
      items:[
        { letters:'ㄳ', word:'넋', pronounced:'넉', mean:'靈魂' },
        { letters:'ㄺ', word:'닭', pronounced:'닥', mean:'雞' },
      ],
    },
    {
      sound:'ㄴ', label:'留下 ㄴ 音',
      items:[
        { letters:'ㄵ', word:'앉다', pronounced:'안따', mean:'坐' },
        { letters:'ㄶ', word:'많다', pronounced:'만타', mean:'多；ㅎ 讓 ㄷ 送氣' },
      ],
    },
    {
      sound:'ㅁ', label:'留下 ㅁ 音',
      items:[
        { letters:'ㄻ', word:'삶', pronounced:'삼', mean:'人生' },
      ],
    },
    {
      sound:'ㄹ', label:'留下 ㄹ 音',
      items:[
        { letters:'ㄼ', word:'여덟', pronounced:'여덜', mean:'八' },
        { letters:'ㄽ', word:'외곬', pronounced:'외골', mean:'單一路向' },
        { letters:'ㄾ', word:'핥다', pronounced:'할따', mean:'舔' },
        { letters:'ㅀ', word:'싫다', pronounced:'실타', mean:'討厭；ㅎ 讓 ㄷ 送氣' },
      ],
    },
    {
      sound:'ㅂ', label:'留下 ㅂ 音',
      items:[
        { letters:'ㅄ', word:'없다', pronounced:'업따', mean:'沒有' },
        { letters:'ㄿ', word:'읊다', pronounced:'읍따', mean:'吟誦' },
      ],
    },
  ],
  doubleBatchimLiaison: [
    { letters:'ㄳ', word:'넋이', pronounced:'넉씨', note:'ㄱ 留下，ㅅ 移到下一格並念緊音' },
    { letters:'ㄵ', word:'앉아', pronounced:'안자', note:'ㄴ 留下，ㅈ 移到下一格' },
    { letters:'ㄺ', word:'닭을', pronounced:'달글', note:'ㄹ 留下，ㄱ 移到下一格' },
    { letters:'ㄻ', word:'젊어', pronounced:'절머', note:'ㄹ 留下，ㅁ 移到下一格' },
    { letters:'ㄿ', word:'읊어', pronounced:'을퍼', note:'ㄹ 留下，ㅍ 移到下一格' },
    { letters:'ㅄ', word:'없어', pronounced:'업써', note:'ㅂ 留下，ㅅ 移到下一格並念緊音' },
    { letters:'ㄶ', word:'많아', pronounced:'마나', note:'ㅎ 消失，ㄴ 接到下一格' },
    { letters:'ㅀ', word:'싫어', pronounced:'시러', note:'ㅎ 消失，ㄹ 接到下一格' },
  ],
  doubleBatchimExceptions: [
    { word:'읽고', pronounced:'일꼬', title:'ㄺ 動詞詞幹＋ㄱ', note:'읽- 後面接 ㄱ 時通常保留 ㄹ，後面的 ㄱ 再變緊音。' },
    { word:'밟다', pronounced:'밥따', title:'밟- 的特別規則', note:'밟- 接子音時多念成 ㅂ 收尾，不照一般 ㄼ 留 ㄹ。' },
  ],
  soundChanges: [
    {
      id:'liaison', label:'連音', badge:'MOVE THE BATCHIM', title:'收尾往下一格滑', article:'標準發音法第 13、14 條',
      summary:'後面音節用 ㅇ 承接母音時，前面的 받침 通常會移到下一格，照原本子音發音。雙收尾則常是一個留下、一個滑過去。',
      cue:'先把下一格的 ㅇ 想成空位：看到母音，就檢查前面的收尾能不能搬過來。',
      examples:[
        { written:'먹어', pronounced:'머거', note:'ㄱ 滑到 어 前面' },
        { written:'집에', pronounced:'지베', note:'ㅂ 滑到 에 前面' },
        { written:'읽어', pronounced:'일거', note:'雙收尾 ㄺ：ㄹ 留下、ㄱ 滑過去' },
        { written:'없어', pronounced:'업써', note:'雙收尾 ㅄ：ㅂ 留下、ㅅ 滑過去並成 ㅆ' },
      ],
    },
    {
      id:'lexical-boundary', label:'代表音後移', badge:'NEUTRALIZE, THEN MOVE', title:'遇到下一個實詞，先變代表音再後移', article:'標準發音法第 15 條',
      summary:'一般語尾或助詞前常照原子音連音；但後面是有實際意思的新詞素時，要先把收尾變成 ㄱ／ㄷ／ㅂ 代表音，再移到下一格。',
      cue:'不要只看下一格是不是 ㅇ；還要分辨它是語尾／助詞，還是另一個有意思的詞。',
      examples:[
        { written:'맛없다', pronounced:'마덥따', note:'ㅅ 收尾先變 ㄷ，再移到 없다，接著緊音化' },
        { written:'겉옷', pronounced:'거돋', note:'ㅌ 收尾先變 ㄷ，再移到 옷' },
        { written:'값어치', pronounced:'가버치', note:'雙收尾只移一個：ㅂ 移到 어 前面' },
      ],
    },
    {
      id:'nasal', label:'鼻音化', badge:'MAKE IT NASAL', title:'卡住的音改走鼻腔', article:'標準發音法第 18、19 條',
      summary:'ㄱ／ㄷ／ㅂ 類收尾遇到 ㄴ、ㅁ 會變成 ㅇ／ㄴ／ㅁ；ㄹ 接在 ㅁ／ㅇ 後面時念 ㄴ，接在 ㄱ／ㅂ 後還會讓前音一起鼻音化。',
      cue:'後面出現 ㄴ、ㅁ 或特定的 ㄹ 時先不要硬爆破；讓相鄰子音一起改走鼻腔。',
      examples:[
        { written:'국물', pronounced:'궁물', note:'ㄱ ＋ ㅁ → ㅇ ＋ ㅁ' },
        { written:'먹는', pronounced:'멍는', note:'ㄱ ＋ ㄴ → ㅇ ＋ ㄴ' },
        { written:'앞문', pronounced:'암문', note:'ㅂ 類收尾 ＋ ㅁ → ㅁ ＋ ㅁ' },
        { written:'담력', pronounced:'담녁', note:'ㅁ 收尾後面的 ㄹ → ㄴ' },
        { written:'석류', pronounced:'성뉴', note:'ㄱ＋ㄹ 先變 ㄱ＋ㄴ，再鼻音化成 ㅇ＋ㄴ' },
      ],
    },
    {
      id:'tense', label:'緊音化', badge:'TIGHTEN IT', title:'六種條件都會讓後音繃緊', article:'標準發音法第 23～28 條',
      summary:'緊音化不只發生在 ㄱ／ㄷ／ㅂ 類收尾後；用言語幹、ㄼ／ㄾ、漢字詞 ㄹ、冠形詞尾 -(으)ㄹ，以及部分複合名詞都有各自條件。',
      cue:'先確認是哪一種條件，再把下一個 ㄱ／ㄷ／ㅂ／ㅅ／ㅈ 短、緊地念出；不是加大音量。',
      examples:[
        { written:'학교', pronounced:'학꾜', note:'第 23 條：ㄱ 類收尾後的 ㄱ → ㄲ' },
        { written:'먹다', pronounced:'먹따', note:'第 23 條：ㄱ 類收尾後的 ㄷ → ㄸ' },
        { written:'잡지', pronounced:'잡찌', note:'第 23 條：ㅂ 類收尾後的 ㅈ → ㅉ' },
        { written:'앉고', pronounced:'안꼬', note:'第 24 條：ㄵ 用言語幹後的 ㄱ → ㄲ' },
        { written:'닮고', pronounced:'담꼬', note:'第 24 條：ㄻ 用言語幹後的 ㄱ → ㄲ' },
        { written:'넓게', pronounced:'널께', note:'第 25 條：ㄼ 用言語幹後的 ㄱ → ㄲ' },
        { written:'핥다', pronounced:'할따', note:'第 25 條：ㄾ 用言語幹後的 ㄷ → ㄸ' },
        { written:'갈등', pronounced:'갈뜽', note:'第 26 條：漢字詞 ㄹ 收尾後的 ㄷ → ㄸ' },
        { written:'발전', pronounced:'발쩐', note:'第 26 條：漢字詞 ㄹ 收尾後的 ㅈ → ㅉ' },
        { written:'할걸', pronounced:'할껄', note:'第 27 條：冠形詞尾 -(으)ㄹ 後的 ㄱ → ㄲ' },
        { written:'할수록', pronounced:'할쑤록', note:'第 27 條：-(으)ㄹ 開頭語尾中的 ㅅ → ㅆ' },
        { written:'문고리', pronounced:'문꼬리', note:'第 28 條：複合名詞後半的 ㄱ → ㄲ' },
        { written:'맘속', pronounced:'맘쏙', note:'第 28 條：複合名詞後半的 ㅅ → ㅆ' },
      ],
    },
    {
      id:'aspiration', label:'送氣化', badge:'ADD THE AIR', title:'遇到 ㅎ，合成送氣音', article:'標準發音法第 12 條',
      summary:'ㄱ／ㄷ／ㅂ／ㅈ 類音和 ㅎ 相遇時，常合成 ㅋ／ㅌ／ㅍ／ㅊ；有些 ㅎ 遇母音則會脫落。',
      cue:'看到 ㅎ 先檢查左右：它可能把鄰居推出一股氣，也可能自己消失。',
      examples:[
        { written:'좋다', pronounced:'조타', note:'ㅎ ＋ ㄷ → ㅌ' },
        { written:'축하', pronounced:'추카', note:'ㄱ ＋ ㅎ → ㅋ' },
        { written:'입학', pronounced:'이팍', note:'ㅂ ＋ ㅎ → ㅍ' },
      ],
    },
    {
      id:'palatal', label:'口蓋音化', badge:'MOVE FOR I', title:'ㄷ／ㅌ 遇 ㅣ，變成 ㅈ／ㅊ', article:'標準發音法第 17 條',
      summary:'ㄷ、ㅌ 類收尾接上以 ㅣ 開始的助詞或接尾詞時，會往 ㅣ 的位置靠近，改念 ㅈ、ㅊ。',
      cue:'看到「ㄷ／ㅌ 받침＋이」先別照普通連音念，優先檢查 ㅈ／ㅊ。',
      examples:[
        { written:'굳이', pronounced:'구지', note:'ㄷ ＋ 이 → 지' },
        { written:'같이', pronounced:'가치', note:'ㅌ ＋ 이 → 치' },
      ],
    },
    {
      id:'liquid', label:'流音化', badge:'TURN N INTO L', title:'ㄴ 與 ㄹ 相遇，先判斷方向', article:'標準發音法第 20 條',
      summary:'ㄴ 在 ㄹ 的前面或後面時通常變成 ㄹ，兩邊念成 ㄹㄹ；但部分漢字詞反過來讓 ㄹ 變 ㄴ，最後念成 ㄴㄴ。',
      cue:'先找相鄰的 ㄴ／ㄹ；一般把 ㄴ 改成 ㄹ。遇到「量、力」等常見例外詞，改查 ㄹ→ㄴ。',
      examples:[
        { written:'난로', pronounced:'날로', note:'一般：ㄴ ＋ ㄹ → ㄹ ＋ ㄹ' },
        { written:'신라', pronounced:'실라', note:'一般：ㄴ ＋ ㄹ → ㄹ ＋ ㄹ' },
        { written:'칼날', pronounced:'칼랄', note:'一般：ㄹ ＋ ㄴ → ㄹ ＋ ㄹ' },
        { written:'물난리', pronounced:'물랄리', note:'一般：ㄹ ＋ ㄴ → ㄹ ＋ ㄹ' },
        { written:'생산량', pronounced:'생산냥', note:'例外：ㄴ 後面的 ㄹ 反而變 ㄴ' },
        { written:'공권력', pronounced:'공꿘녁', note:'例外：先緊音化，再把 ㄹ 變 ㄴ' },
      ],
    },
    {
      id:'n-insertion', label:'ㄴ 添加音', badge:'ADD AN N', title:'複合詞遇 이／야／여／요／유，加一個 ㄴ', article:'標準發音法第 29 條',
      summary:'前半以子音收尾、後半以 이 或 y 系母音開始時，複合詞與派生詞常先加入 ㄴ，再發生鼻音化或流音化。',
      cue:'看到「收尾＋이／야／여／요／유」先別直接連音；如果是兩個詞結合，優先檢查 ㄴ 添加音。',
      examples:[
        { written:'꽃잎', pronounced:'꼰닙', note:'잎 前加 ㄴ，再由 ㄷ 類收尾鼻音化成 ㄴ' },
        { written:'담요', pronounced:'담뇨', note:'요 前加入 ㄴ：요 → 뇨' },
        { written:'물약', pronounced:'물략', note:'약 前加 ㄴ，再受 ㄹ 收尾影響念成 ㄹ' },
      ],
    },
    {
      id:'saisiot', label:'사이시옷', badge:'THE HIDDEN S', title:'有 ㅅ 的複合詞，後音可能緊化或加 ㄴ', article:'標準發音法第 30 條',
      summary:'사이시옷 遇 ㄱ／ㄷ／ㅂ／ㅅ／ㅈ 時通常讓後音變緊；遇 ㄴ／ㅁ 時念成 ㄴ；遇 이 音時會形成 ㄴㄴ。',
      cue:'字中間看見 ㅅ 收尾，不要固定念 s；先看後半第一個聲音。',
      examples:[
        { written:'냇가', pronounced:'내까', note:'後面的 ㄱ 變 ㄲ；[낻까] 也屬標準讀法' },
        { written:'콧날', pronounced:'콘날', note:'사이시옷 在 ㄴ 前鼻音化成 ㄴ' },
        { written:'깻잎', pronounced:'깬닙', note:'이 音前加入 ㄴ，形成 ㄴㄴ' },
      ],
    },
    {
      id:'vowel-rules', label:'母音標準讀法', badge:'READ THE VOWEL', title:'字一樣，位置會決定母音讀法', article:'標準發音法第 4、5、22 條',
      summary:'져／쪄／쳐 的活用形念 저／쩌／처；子音初聲後的 ㅢ 必須念 ㅣ。ㅚ／ㅟ 與部分 ㅖ、의、되어／피어另有允許讀法。',
      cue:'先記強制規則，再把斜線後面的讀法當成「兩種都標準」，不要誤判成錯音。',
      examples:[
        { written:'가져', pronounced:'가저', note:'活用形 져 → 저' },
        { written:'다쳐', pronounced:'다처', note:'活用形 쳐 → 처' },
        { written:'희망', pronounced:'히망', note:'子音初聲 ㅎ 後的 ㅢ 必須念 ㅣ' },
        { written:'주의', pronounced:'주의／주이', note:'非詞首 의 可保留 의，也可念 이', quiz:false },
        { written:'시계', pronounced:'시계／시게', note:'예／례 以外的 ㅖ 可念 ㅔ', quiz:false },
        { written:'되어', pronounced:'되어／되여', note:'되-＋어 原則照字讀，也允許加入 y 音', quiz:false },
        { written:'회', pronounced:'회／훼', note:'ㅚ 原則是單母音，也允許念成近 ㅞ 的雙母音', quiz:false },
      ],
    },
    {
      id:'letter-names', label:'字母名稱連音', badge:'NAME THE LETTER', title:'七個字母名稱有自己的特殊連音', article:'標準發音法第 16 條',
      summary:'ㄷ、ㅈ、ㅊ、ㅋ、ㅌ、ㅍ、ㅎ 的字母名稱接 이／을／에 時，不完全照一般連音，要使用規定的子音。',
      cue:'這是「字母名稱」專用規則；不要把 디귿이 的念法套到所有普通單字。',
      examples:[
        { written:'디귿이', pronounced:'디그시', note:'디귿＋이：末尾 ㄷ 特別連成 ㅅ' },
        { written:'지읒이', pronounced:'지으시', note:'지읒＋이：末尾 ㅈ 特別連成 ㅅ' },
        { written:'치읓이', pronounced:'치으시', note:'치읓＋이：末尾 ㅊ 特別連成 ㅅ' },
        { written:'키읔이', pronounced:'키으기', note:'키읔＋이：末尾 ㅋ 連成 ㄱ' },
        { written:'티읕이', pronounced:'티으시', note:'티읕＋이：末尾 ㅌ 特別連成 ㅅ' },
        { written:'피읖이', pronounced:'피으비', note:'피읖＋이：末尾 ㅍ 連成 ㅂ' },
        { written:'히읗이', pronounced:'히으시', note:'히읗＋이：末尾 ㅎ 特別連成 ㅅ' },
      ],
    },
    {
      id:'vowel-length', label:'母音長短', badge:'HOLD THE FIRST BEAT', title:'規範保留長短音，通常出現在第一音節', article:'標準發音法第 6、7 條',
      summary:'標準發音法仍標示母音長短；長音原則上出現在單字第一音節。現代首爾口語常不明顯，因此本課以「認得規範標記」為主。',
      cue:'畫面中的 ː 表示把前面的母音稍微拉長；不用為了長音破壞整句自然節奏。',
      examples:[
        { written:'말씨', pronounced:'말ː씨', note:'第一音節的 ㅏ 是規範長音', quiz:false },
        { written:'밤나무', pronounced:'밤ː나무', note:'第一音節的 ㅏ 是規範長音', quiz:false },
        { written:'반신반의', pronounced:'반ː신바ː늬／반ː신바ː니', note:'複合詞第二部分也可能保留明顯長音', quiz:false },
      ],
    },
  ],
};
